repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        name: flake8-syntax
        args: [--count, '--select=E9,F63,F7,F82', --show-source, --statistics, --builtins="_"]
    -   id: flake8
        name: flake8-style
        args: [--count, --max-complexity=10, --max-line-length=88, --statistics]
